steps:
 - name: europe-west3-docker.pkg.dev/li-soft/lsml-ci/oracle-jdk8-builder:live
   entrypoint: 'chmod'
   args: ['+x', 'gradlew']
 - name: europe-west3-docker.pkg.dev/li-soft/lsml-ci/oracle-jdk8-builder:live
   entrypoint: './gradlew'
   args: ['check']
