steps:
  # We need a full git tree for "ratchedFrom" to work in spotless plugin.
  - name: 'gcr.io/cloud-builders/git'
    args: [ 'fetch', '--unshallow' ]
  # For some reason, the gradle script is not set as executable despite it being marked so in git
  - name: eclipse-temurin:17
    entrypoint: 'chmod'
    args: [ '+x', 'gradlew' ]
  - name: eclipse-temurin:17
    entrypoint: './gradlew'
    args: [ 'check' ]
